## [1] matrix dot

### (1). Neighborhood-Based CF

+ mean-centered rating $s_{uj} = r_{uj} - \mu_u$를 이용



#### (a) Item based CF

+ $$AdjustedCosine(i,j) = \cfrac{\sum_{u\in U_i \cap U_j} s_{ui} \cdot s_{uj} }{\sqrt{\sum_{u\in U_i \cap U_j} s_{ui}^2 } \cdot \sqrt{\sum_{u\in U_i \cap U_j} s_{uj}^2 } }$$ , where $U_i$ 는 item i를 평가한 user set

+ $Q_t(u)$ : user u가 평가한 item 중, target item t와 가장 similar한 top k개 item set

+ user u의 item t에 관한 예측값 $\hat{r}_{ut}=\cfrac{\sum_{j \in Q_t(u)}AdjustedCosine(j,t) \cdot r_{uj}}{\sum_{j\in Q_t(u)}|AdjustedCosine(j,t)|}$

  + basic concept은 user u의 item t에 대한 rating 예측을 할 때,  user u가 rating한 것의 가중평균을 이용한다는 것


+ similarity
    + row : user가 rating한 item
    + col : 전체 item
    + value : 두 item 간의 similarity

+ rating
    + user가 rating한 item의 rating


+ 전체 item에 대한 user의 rating 예측값을 구하는 것이 목적
    + 각 item에 대해서, user의 rating과 similarity를 가중평균 해야 함

In [ ]:
# 1. 데이터 생성하기
import numpy as np
similarity = np.array([[-3,3,4],[100,100,100]])
rating = np.array([3,4])
print(similarity)
print(rating)
print(rating.T)

[[ -3   3   4]
 [100 100 100]]
[3 4]
[3 4]


In [ ]:
# 2. 곱하여 가중합 구하기
## [1] 방법 1
print(np.matmul(rating.T, similarity ))

## [2] 방법 2
weighted_sum = rating.T.dot(similarity)
print(weighted_sum)

[391 409 412]
[391 409 412]


In [ ]:
# 3. similarity의 절대값 합으로 나눠주기
## [1] col 별로 절대값 합 구하기
abs_sum = np.absolute(similarity).sum(axis=0)
print(abs_sum)

## [2] 절대값 합으로 나눠주기
print(weighted_sum/abs_sum)

[103 103 104]
[3.7961165  3.97087379 3.96153846]
